FROM rust:1.85-slim

RUN apt-get update && apt-get install -y pkg-config libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*
RUN cargo install sqlx-cli --no-default-features --features postgres

CMD ["sqlx", "migrate", "run"]
