[[stations]]
id   = 1
name = "Labinstica"
addr = "192.168.55.161:4712"

[[stations]]
id   = 2
name = "VDG"
addr = "192.168.52.161:4712"

[[stations]]
id   = 3
name = "Ucka"
addr = "192.168.61.161:4712"

[[stations]]
id   = 4
name = "Osor"
addr = "192.168.66.161:4712"


[[stations]]
id   = 5
name = "Ilijino Brdo"
addr = "192.168.74.161:4712"

[[stations]]
id   = 6
name = "Lastovo"
addr = "192.168.73.161:4712"

[[stations]]
id   = 7
name = "Savurija"
addr = "192.168.64.161:4712"

[[stations]]
id   = 8
name = "SvMihovil"
addr = "192.168.55.161:4712"

[[stations]]
id   = 9
name = "Kamenari"
addr = "192.168.81.251:4712"